version: '2'
services:

  selenium-hub:
      container_name: selenium-hub
      image: selenium/hub:3.0.1-aluminum
      environment:
          - "TZ=${TZ}"
      ports:
          - "4444:4444"
      network_mode: bridge

  selenium-firefox:
      container_name: selenium-firefox
      image: selenium/node-firefox-debug:3.0.1-aluminum
      environment:
          - "TZ=${TZ}"
          - "HUB_PORT_4444_TCP_ADDR=selenium-hub.hub.cloud.unit"
          - "HUB_PORT_4444_TCP_PORT=4444"
      ports:
          - "5900:5900"
      network_mode: bridge
      depends_on:
          - selenium-hub

  selenium-chrome:
      container_name: selenium-chrome
      image: selenium/node-chrome-debug:3.0.1-aluminum
      environment:
          - "TZ=${TZ}"
          - "HUB_PORT_4444_TCP_ADDR=selenium-hub.hub.cloud.unit"
          - "HUB_PORT_4444_TCP_PORT=4444"
      ports:
          - "5901:5900"
      network_mode: bridge
      depends_on:
          - selenium-hub
